---
build_from:
  armv7: "ghcr.io/hassio-addons/debian-base/armv7:7.1.0"
  aarch64: "ghcr.io/hassio-addons/debian-base/aarch64:7.1.0"
  amd64: "ghcr.io/hassio-addons/debian-base/amd64:7.1.0"
  i386: "ghcr.io/hassio-addons/debian-base/i386:7.1.0"
