---
build_from:
  armv7: "ghcr.io/home-assistant/arm32v7-base-debian:buster"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:buster"
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:buster"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:buster"
  i386: "ghcr.io/home-assistant/i386-base-debian:buster"
