---
name: Wallabag
version: dev
slug: wallabag
description: A web application allowing you to save web pages for later reading
url: "https://github.com/coostax/addon-wallabag"
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
services:
  - mysql:want
arch:
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
map:
  - ssl
ports:
  80/tcp: 8000
ports_description:
  80/tcp: Web interface
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  twofactor_auth: true
schema:
  remote_mysql_host: str?
  remote_mysql_database: str?
  remote_mysql_username: str?
  remote_mysql_password: password?
  remote_mysql_port: int?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  certfile: str
  keyfile: str
  ssl: bool
  token_secret: str?
  app_url: str?
  app_name: str?
  locale: list(en|pt-PT)?
  twofactor_auth: bool
  twofactor_sender: str?
init: false
# image: "ghcr.io/coostax/wallabox/{arch}"
