---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: coostax/ghactions-workflows/.github/workflows/ha-addon-ci.yaml@main
    with:
      slug: "wallabag"
      ghcr_repo: "coostax"
